"use client";
import { AnimatePresence, motion } from "motion/react";
import { Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { ProductMediaPlaceholder } from "@/components/product/product-media-placeholder";
import { ProductCard } from "@/components/product/product-card";
import { useBag } from "@/lib/commerce/bag-store";
import { calculateCartTotals, resolveCartItems } from "@/lib/commerce/cart";
import { formatMoney } from "@/lib/commerce/money";
import { normalizePromoCode } from "@/lib/commerce/promo";
import { mockProducts } from "@/data/mock-products";
import { MAX_CART_QUANTITY } from "@/config/commerce";

export function CartPage(){const bag=useBag();const resolved=resolveCartItems(bag.items);const [promoInput,setPromoInput]=useState("");const [promoCode,setPromoCode]=useState("");const [promoMessage,setPromoMessage]=useState("");const [announcement,setAnnouncement]=useState("");const totals=calculateCartTotals(resolved.lines,promoCode,"standard");const recommendations=useMemo(()=>mockProducts.filter((product)=>!bag.items.some((item)=>item.productId===product.id)).slice(0,4),[bag.items]);function applyPromo(event){event.preventDefault();const code=normalizePromoCode(promoInput);const result=calculateCartTotals(resolved.lines,code,"standard").promo;if(result?.valid){setPromoCode(code);setPromoMessage("CODE APPLIED")}else{setPromoCode("");setPromoMessage(result?.message||"Enter a promo code.")}}return <main id="main" className="container-shell min-h-[75vh] pb-24 pt-28"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow text-muted-foreground">Anonymous commerce</p><h1 className="section-title mt-3">YOUR BAG</h1></div><p className="eyebrow">{bag.count} {bag.count===1?"ITEM":"ITEMS"}</p></div>{resolved.errors.length>0&&<div role="alert" className="mt-8 border border-amber-600 bg-amber-50 p-4"><strong>YOUR BAG NEEDS ATTENTION.</strong><ul className="mt-2 list-disc pl-5 text-sm">{resolved.errors.map((error,index)=><li key={`${error.code}-${index}`}>{error.message}</li>)}</ul></div>}{resolved.lines.length?<><div className="mt-10 grid gap-10 lg:grid-cols-[minmax(0,1fr)_23rem]"><section aria-label="Cart items"><AnimatePresence initial={false}>{resolved.lines.map((line)=><CartItem key={line.key} line={line} bag={bag} announce={setAnnouncement}/>)}</AnimatePresence></section><CartSummary totals={totals} promoInput={promoInput} setPromoInput={setPromoInput} promoMessage={promoMessage} applyPromo={applyPromo} itemCount={bag.count} canCheckout={!resolved.errors.length}/></div><section className="mt-24"><p className="eyebrow text-muted-foreground">Continue exploring</p><h2 className="mt-3 font-display text-4xl font-semibold tracking-[-.05em]">YOU MAY ALSO LIKE</h2><div className="mt-8 grid grid-cols-2 gap-4 md:grid-cols-4">{recommendations.map((product,index)=><ProductCard key={product.id} product={product} index={index}/>)}</div></section></>:<EmptyCart/>}<p className="sr-only" aria-live="polite">{announcement}</p></main>}
function CartItem({line,bag,announce}){const {product,variant}=line;function quantity(next){bag.setQuantity(line.key,next);announce(`Quantity updated to ${next}.`)}function updateVariant(id){const next=product.variants.find((entry)=>entry.id===id);const same=next.sizes.find((entry)=>entry.value===line.size&&entry.inStock);const fallback=next.sizes.find((entry)=>entry.inStock);if(fallback)bag.update(line.key,{variantId:id,size:same?line.size:fallback.value})}return <motion.article layout exit={{opacity:0,y:-8}} transition={{duration:.18}} className="grid gap-5 border-t border-border py-6 sm:grid-cols-[10rem_1fr]"><ProductMediaPlaceholder product={product} color={variant.color} className="aspect-square"/><div className="min-w-0"><div className="flex justify-between gap-4"><div><Link href={`/product/${product.slug}`} className="font-display text-2xl font-semibold">{product.name}</Link><p className="mt-1 text-sm text-muted-foreground">{product.subtitle}</p></div><strong>{formatMoney(line.unitPriceCents*line.quantity)}</strong></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">COLOR<select value={variant.id} onChange={(event)=>updateVariant(event.target.value)} className="mt-2 min-h-11 w-full border border-border bg-transparent px-3">{product.variants.map((entry)=><option key={entry.id} value={entry.id}>{entry.color.name}</option>)}</select></label><label className="text-xs font-semibold">SIZE<select value={line.size} onChange={(event)=>bag.update(line.key,{size:Number(event.target.value)})} className="mt-2 min-h-11 w-full border border-border bg-transparent px-3">{variant.sizes.map((size)=><option key={size.value} value={size.value} disabled={!size.inStock}>US {size.value}{!size.inStock?" — unavailable":""}</option>)}</select></label></div><div className="mt-5 flex flex-wrap items-center justify-between gap-4"><div className="flex items-center border border-black"><button type="button" disabled={line.quantity<=1} onClick={()=>quantity(line.quantity-1)} className="grid size-11 place-items-center disabled:opacity-30" aria-label={`Decrease ${product.name} quantity`}><Minus size={16}/></button><span className="min-w-10 text-center" aria-label={`Quantity ${line.quantity}`}>{line.quantity}</span><button type="button" disabled={line.quantity>=MAX_CART_QUANTITY} onClick={()=>quantity(line.quantity+1)} className="grid size-11 place-items-center disabled:opacity-30" aria-label={`Increase ${product.name} quantity`}><Plus size={16}/></button></div><button onClick={()=>{bag.remove(line.key);announce(`${product.name} removed from bag.`)}} className="flex min-h-11 items-center gap-2 text-xs font-semibold underline"><Trash2 size={15}/> REMOVE</button></div></div></motion.article>}
function CartSummary({totals,promoInput,setPromoInput,promoMessage,applyPromo,itemCount,canCheckout}){return <aside className="h-fit border border-border bg-white p-5 lg:sticky lg:top-24"><h2 className="font-display text-2xl font-semibold">ORDER SUMMARY</h2><dl className="mt-6 space-y-3 text-sm"><Row label="Subtotal" value={formatMoney(totals.subtotalCents)}/><Row label="Discount" value={totals.discountCents?`−${formatMoney(totals.discountCents)}`:"—"}/><Row label="Estimated shipping" value={totals.shippingCents?formatMoney(totals.shippingCents):"FREE"}/><Row label="Estimated tax" value={totals.estimatedTaxCents?formatMoney(totals.estimatedTaxCents):"Calculated later"}/><div className="border-t border-black pt-4 text-base font-semibold"><Row label="Total" value={formatMoney(totals.totalCents)}/></div></dl><form onSubmit={applyPromo} className="mt-6"><label className="text-xs font-semibold" htmlFor="promo">PROMO CODE</label><div className="mt-2 flex"><input id="promo" value={promoInput} onChange={(event)=>setPromoInput(event.target.value.slice(0,32))} autoCapitalize="characters" className="min-h-12 min-w-0 flex-1 border border-black px-3"/><button className="min-h-12 bg-black px-4 text-xs font-semibold text-white">APPLY</button></div><p className={`mt-2 min-h-5 text-xs ${totals.promo?.valid?"text-green-700":"text-red-700"}`} role="status">{promoMessage}</p></form>{canCheckout?<Link href="/checkout" className="mt-6 flex min-h-14 items-center justify-center bg-black px-5 font-semibold text-white">CHECKOUT · {itemCount} {itemCount===1?"ITEM":"ITEMS"}</Link>:<button disabled className="mt-6 min-h-14 w-full bg-black text-white opacity-40">RESOLVE BAG ISSUES</button>}<p className="mt-3 text-xs leading-5 text-muted-foreground">Totals are estimates. The server will revalidate products, inventory, promotions and pricing before payment.</p></aside>}
function Row({label,value}){return <div className="flex justify-between gap-4"><dt>{label}</dt><dd>{value}</dd></div>}
function EmptyCart(){return <div className="grid min-h-96 place-items-center text-center"><div><ShoppingBag className="mx-auto" size={34}/><h2 className="mt-5 font-display text-4xl font-semibold">YOUR BAG IS EMPTY.</h2><p className="mt-2 text-muted-foreground">Explore something worth moving in.</p><div className="mt-7 flex flex-col justify-center gap-2 sm:flex-row"><Link href="/shop/new-releases" className="flex min-h-12 items-center justify-center bg-black px-6 text-sm font-semibold text-white">SHOP NEW RELEASES</Link><Link href="/shop/running" className="flex min-h-12 items-center justify-center border border-black px-6 text-sm font-semibold">SHOP RUNNING</Link></div></div></div>}