"use client";
import { useSyncExternalStore } from "react";
import { CART_STORAGE_KEY, CART_STORAGE_VERSION, MAX_CART_QUANTITY } from "@/config/commerce";
import { cartLineKey } from "./cart";
let items = [], loaded = false;
const listeners = new Set();
function sanitize(item) { if (!item || typeof item.productId !== "string" || typeof item.variantId !== "string" || !Number.isFinite(item.size)) return null; const quantity = Number.isInteger(item.quantity) ? Math.max(1, Math.min(MAX_CART_QUANTITY, item.quantity)) : 1; return { productId: item.productId, variantId: item.variantId, size: item.size, quantity }; }
function load() { if (loaded || typeof window === "undefined") return; loaded = true; try { const current = JSON.parse(localStorage.getItem(CART_STORAGE_KEY) || "null"); const legacy = JSON.parse(localStorage.getItem("solvyn:bag") || "null"); const source = current?.version === CART_STORAGE_VERSION && Array.isArray(current.items) ? current.items : Array.isArray(legacy) ? legacy : []; items = source.map(sanitize).filter(Boolean).slice(0,50); persist(); if (legacy) localStorage.removeItem("solvyn:bag"); } catch { items=[]; try { localStorage.removeItem(CART_STORAGE_KEY); } catch {} } }
function persist() { try { localStorage.setItem(CART_STORAGE_KEY,JSON.stringify({version:CART_STORAGE_VERSION,items})); return true; } catch { return false; } }
function emit(){listeners.forEach((listener)=>listener())}
function subscribe(listener){load();listeners.add(listener);return()=>listeners.delete(listener)}
function snapshot(){load();return JSON.stringify(items)}
function mergeLines(next){const merged=[];for(const item of next){const match=merged.find((entry)=>cartLineKey(entry)===cartLineKey(item));if(match)match.quantity=Math.min(MAX_CART_QUANTITY,match.quantity+item.quantity);else merged.push({...item});}return merged;}
export function useBag(){const value=useSyncExternalStore(subscribe,snapshot,()=>"[]");const bagItems=JSON.parse(value);function commit(next){items=mergeLines(next.map(sanitize).filter(Boolean));const saved=persist();emit();return saved;}return{items:bagItems,count:bagItems.reduce((sum,item)=>sum+item.quantity,0),add(item){load();return commit([...items,{...sanitize(item),quantity:1}])},remove(key){load();return commit(items.filter((item)=>cartLineKey(item)!==key))},setQuantity(key,quantity){load();return commit(items.map((item)=>cartLineKey(item)===key?{...item,quantity:Math.max(1,Math.min(MAX_CART_QUANTITY,Number(quantity)||1))}:item))},update(key,patch){load();return commit(items.map((item)=>cartLineKey(item)===key?{...item,...patch}:item))},clear(){return commit([])}}}