"use client";
import Link from "next/link";
import * as Dialog from "@radix-ui/react-dialog";
import { AnimatePresence, motion, useReducedMotion, useScroll, useMotionValueEvent } from "motion/react";
import { Menu, Search, ShoppingBag, User, Heart, X } from "lucide-react";
import { useState } from "react";
import { Wordmark } from "@/components/brand/wordmark";
import { primaryNavigation } from "@/lib/constants/navigation";
export function SiteHeader() { const [compact, setCompact] = useState(false); const [open, setOpen] = useState(false); const reduced = useReducedMotion(); const { scrollY } = useScroll(); useMotionValueEvent(scrollY, "change", v => setCompact(v > 48)); return <motion.header layout className={`fixed inset-x-0 top-0 z-50 mx-auto transition-[padding] ${compact ? "p-2 md:p-3" : "p-0"}`}><motion.div layout className={`mx-auto flex h-16 max-w-[96rem] items-center justify-between px-4 text-white transition-[background,border-radius,border-color,box-shadow] md:px-6 ${compact ? "rounded-[1.25rem] border border-white/15 bg-black/80 shadow-xl backdrop-blur-md" : "border-transparent bg-gradient-to-b from-black/60 to-transparent"}`}><Link href="/" aria-label="SOLVYN home"><Wordmark /></Link><nav aria-label="Primary" className="hidden lg:block"><ul className="flex items-center gap-5 xl:gap-7">{primaryNavigation.map(i => <li key={i.href}><Link className="group relative py-3 text-[.68rem] font-semibold tracking-[.08em]" href={i.href}>{i.label.toUpperCase()}<span className="absolute inset-x-0 bottom-1 h-px origin-left scale-x-0 bg-[#c7ff2f] transition-transform group-hover:scale-x-100"/></Link></li>)}</ul></nav><div className="flex items-center gap-1"><Utility href="/search" label="Search" icon={<Search />}/><span className="hidden md:contents"><Utility href="/account" label="Account" icon={<User />}/><Utility href="/wishlist" label="Wishlist" icon={<Heart />}/></span><Utility href="/cart" label="Bag" icon={<ShoppingBag />}/><Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger asChild><button className="grid size-11 place-items-center lg:hidden" aria-label="Open menu"><Menu /></button></Dialog.Trigger><AnimatePresence>{open && <Dialog.Portal forceMount><Dialog.Overlay asChild><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[60] bg-black/55"/></Dialog.Overlay><Dialog.Content asChild onOpenAutoFocus={e => { if (reduced)
    e.preventDefault(); }}><motion.div initial={reduced ? { opacity: 0 } : { x: "100%" }} animate={{ x: 0, opacity: 1 }} exit={reduced ? { opacity: 0 } : { x: "100%" }} transition={{ duration: reduced ? .1 : .38, ease: [.22, 1, .36, 1] }} className="fixed inset-y-0 right-0 z-[61] flex w-full max-w-[34rem] flex-col bg-[#0a0a0a] p-5 text-white"><div className="flex h-12 items-center justify-between"><Dialog.Title><Wordmark /></Dialog.Title><Dialog.Close className="grid size-11 place-items-center" aria-label="Close menu"><X /></Dialog.Close></div><nav className="mt-10" aria-label="Mobile primary"><motion.ul initial="hidden" animate="show" variants={{ show: { transition: { staggerChildren: reduced ? 0 : .04 } } }}>{primaryNavigation.map((i, n) => <motion.li key={i.href} variants={{ hidden: { opacity: 0, y: 12 }, show: { opacity: 1, y: 0 } }}><Link onClick={() => setOpen(false)} className="flex min-h-14 items-center justify-between border-b border-white/15 font-display text-[clamp(1.6rem,7vw,2.8rem)] font-medium tracking-[-.04em]" href={i.href}>{i.label}<span className="eyebrow text-white/35">0{n + 1}</span></Link></motion.li>)}</motion.ul></nav><div className="mt-auto grid grid-cols-2 gap-2 pt-8"><Link href="/account" className="flex min-h-12 items-center gap-2 border border-white/20 px-4"><User size={18}/> Account</Link><Link href="/wishlist" className="flex min-h-12 items-center gap-2 border border-white/20 px-4"><Heart size={18}/> Wishlist</Link></div></motion.div></Dialog.Content></Dialog.Portal>}</AnimatePresence></Dialog.Root></div></motion.div></motion.header>; }
function Utility({ href, label, icon }) { return <Link className="grid size-11 place-items-center [&_svg]:size-[19px]" href={href} aria-label={label}>{icon}</Link>; }
